name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build -t my-app-image .

      # Step 5: Run Tests (if applicable)
      # - name: Run Tests
      #   run: npm test

      # Step 6: Start the Application
      - name: Run Application
        run: docker run -d -p 3000:3000 my-app-image
